services:
  
  kratos-logs:
    image: datalust/seq:latest
    container_name: kratos_seq
    ports:
      - "5341:80"
      - "12345:5341"
    environment:
      - ACCEPT_EULA=Y
      - SEQ_FIRSTRUN_NOAUTHENTICATION=true
    volumes:
      - ./seq-data:/data
    networks:
      - kratos-net

  kratos-monitor:
    image: xabarilcoding/healthchecksui:latest
    container_name: kratos_monitor
    ports:
      - "5008:80"
    environment:
      # Formato de variáveis de ambiente para o HealthChecksUI
      - HealthChecksUI__HealthChecks__0__Name=Kratos - Liveness
      - HealthChecksUI__HealthChecks__0__Uri=http://host.docker.internal:5007/health/live
      - HealthChecksUI__HealthChecks__1__Name=Kratos - Readiness
      - HealthChecksUI__HealthChecks__1__Uri=http://host.docker.internal:5007/health/ready
      # Opcional: Define o intervalo de atualização (em segundos)
      - HealthChecksUI__EvaluationTimeInSeconds=10
    networks:
      - kratos-net

  kratos-worker:
    build: ./kratos-worker
    container_name: kratos_worker
    restart: always
    depends_on:
      rabbitmq:
        condition: service_healthy
      mongodb:
        condition: service_started
      redis:
        condition: service_started
    environment:
      - MONGO_URL=mongodb://root:example@mongodb:27017
      - REDIS_URL=redis:6379
      - RABBIT_URL=amqp://guest:guest@rabbitmq:5672
    networks:
      - kratos-net

  kratos-front:
    build: ./kratos-front
    container_name: kratos_front
    ports:
      - "3000:80"
    networks:
      - kratos-net

  rabbitmq:
    image: rabbitmq:3-management
    container_name: kratos_rabbit
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - kratos-net

  mongodb:
    image: mongo:latest
    container_name: kratos_mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example
    ports:
      - "27017:27017"
    networks:
      - kratos-net

  redis:
    image: redis:alpine
    container_name: kratos_redis
    ports:
      - "6379:6379"
    networks:
      - kratos-net

networks:
  kratos-net:
    driver: bridge